<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <ReferenceXUnitWrapperGenerator>false</ReferenceXUnitWrapperGenerator>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <CLRTestExecutionArguments>99</CLRTestExecutionArguments>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="HighMemoryPercent.cs" />
    <RuntimeHostConfigurationOption Include="System.GC.HighMemoryPercent" Value="100" />
  </ItemGroup>
</Project>
