<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestExecutionArguments />
    <!-- Satori NYI multiple latency modes -->
    <DisableProjectBuild>true</DisableProjectBuild>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="InputValidation.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
